### ISSUE TITLE
Mixed line endings not reported accurately

### ISSUE THREAD

**Issue by AArnott** [jhartell/vscode-line-endings#1]
In a file of mixed line endings, this extension still renders all the line endings as if they were consistent. That is, if VS Code considers it a CRLF file, all line endings are rendered as if they were CRLF, instead of showing a few lines as just LF as they actually are.

**Comment by jhartell** [comment]
It appears that VS Code normalizes line endings automatically whenever a file is opened, based on this discussion: https://github.com/Microsoft/vscode/issues/127

I did a quick test with the following file:
```
CRLF 1\r\n
CRLF 2\r\n
CRLF 3\r\n
LF 1\n
LF 2\n
```
Debugging the output of `vscode.window.activeTextEditor.document.getText()` when the file is opened shows that the line endings have indeed already been normalized:
![normalized_endings](https://user-images.githubusercontent.com/2088545/59717360-80dbad80-9220-11e9-8c1d-8f3ca6bd5699.png)

So unfortunately there is currently no way for the extension to render this correctly.
